### ISSUE TITLE
Missing icon in hamburgerIcon component

### ISSUE THREAD

**Issue by ralphiz** [andrewyeex/mycloset#12]
Getting this error when trying to run `npm start`:
![image](https://user-images.githubusercontent.com/3977903/51421707-21854e80-1b57-11e9-93c7-c73e20f3cf82.png)

**Comment by andrewyeex** [comment]
@ralphiz  https://github.com/iconic/open-iconic/archive/master.zip dowload link for the open-iconic-master folder and save into utilities folder

**Comment by ralphiz** [comment]
alright, thanks @andrewyeex !
